config/routes.rb
Rails.application.routes.draw do

  get 'reset_passwords/new'

  get 'pages/home'
  get 'pages/contact'
  get 'pages/help'

  root to: 'pages#home'

  resources :users do
    member do
      get :activate
    end
  end
  resources :products
  resources :sessions
  resources :reset_passwords, only: [:new, :create, :update, :edit]

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

  get       'signup', to:   'users#new',  as: :signup
  get       'login',  to:   'sessions#new',       as: :login
  post      'login',  to:   'sessions#create'
  delete    'logout', to:   'sessions#destroy',   as: :logout

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  acts_as_messageable
  has_many :products, dependent: :destroy
  before_save { self.email = email.downcase }
  mount_uploader :picture, PictureUploader

  validates :password, presence: true, length: { minimum: 3 }, confirmation: true, if: :new_user?
  validates :email, uniqueness: true, email_format: { message: 'has invalid format' }
  validates :name, presence: true, length: { minimum:4 }
  validate :picture_size


  class << self
    def current_users
      where("#{sorcery_config.last_activity_at_attribute_name} IS NOT NULL") \
      .where("#{sorcery_config.last_logout_at_attribute_name} IS NULL
      OR #{sorcery_config.last_activity_at_attribute_name} > #{sorcery_config.last_logout_at_attribute_name}") \
      .where("#{sorcery_config.last_activity_at_attribute_name} > ? ", sorcery_config.activity_timeout.seconds.ago.utc.to_s(:db))
    end
  end

  def mailboxer_email(object)
    #Check if an email should be sent for that object
      #if true
        return email
      #if false
        #return nil
    end


  private

  def new_user?
    new_record?
  end

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :current_user?, only: [:edit, :update, :destroy]
  skip_before_filter :require_login, only: [:new, :create, :show]
  # GET /users
  # GET /users.json
  def index
      @users = User.paginate(page: params[:page], per_page: 25)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { login(params[:user][:email], params[:user][:password])
                      flash[:success] = "Registration successful. Please check your email for activation."
                      redirect_back_or_to @user  }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { flash[:danger] = "Registration failed. Please check the data you introduced."
                      render :new   }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { flash[:success] = "Profile successfully updated"
                      redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { flash[:danger] = "Edit profile failed. Please check the data you introduced."
                      render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { flash[:success] = "User deleted."
                    redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def activate
    if @user = User.load_from_activation_token(params[:id])
      @user.activate!
      flash[:success] = 'User was successfully activated.'
      redirect_to @user
    else
      flash[:warning] = 'Cannot activate this user.'
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :picture)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def activated_user
    unless current_user.activation_state == "active" || current_user.admin
      flash[:danger] = "Please activate your account"
      redirect_to products_path
    end
  end

  def correct_user
    unless current_user.admin? || @product = current_user.products.find_by(id: params[:id])
      flash[:danger] = "You don't have the rights to do that!"
      redirect_to products_path
    end
  end

  def current_user?
    unless current_user == User.find_by(id: params[:id]) || current_user.admin
      flash[:danger] = "You don't have the rights to do that!"
      if logged_in?
        redirect_to users_path
      else
        redirect_to root_url
      end
    end
  end
end

app/views/users/_form.html.haml
.row
  = form_for(@user, html: { class: 'col s12 m6 offset-m3 l4 offset-l4', multipart: true } ) do |f|
    = render 'shared/errors'
    .row
      .input-field.col.s12
        = f.text_field :name, class: 'validate', required: true, autofocus: true
        %label{:for => "name"} Name
    .row
      .input-field.col.s12
        = f.email_field :email, class: 'validate', required: true
        %label{:for => "email"} Email
    .row
      .input-field.col.s12
        = f.password_field :password, class: 'validate', required: true
        %label{:for => "password"} Password
    .row
      .input-field.col.s12
        = f.password_field :password_confirmation, class: 'validate', required: true
        %label{:for => "password_confirmation"} Confirm password
    = f.submit class: 'waves-effect waves-light btn'

app/views/users/edit.html.haml
.container
  .row.center-align
    .col.s12.m6.offset-m3.l4.offset-l4
      %h1.orange-text Edit your profile
  = render 'form'
  .row.center-align
    .col.s12.m6.offset-m3.l4.offset-l4
      = link_to 'Show', @user, class: 'waves-effect waves-light btn'
      = link_to 'Back', users_path, class: 'waves-effect waves-light btn'

app/views/users/index.html.haml
%p#notice= notice
.col-md-offset-2.col-md-8.col-sm-12.col-xs-12
  %h1 Listing Users
  = will_paginate
  %table.table.table-striped
    %thead
      %tr
        %th
        %th Name
        %th{:colspan => "2"}
    %tbody
      - @users.each do |user|
        %tr
          %td#profile-picture
            = image_tag(user.picture, size:'40x40', class: 'img-circle') if user.picture?
            = image_tag("#{asset_path('users/image_missing.jpg')}", size: '40x40', class: 'img-circle') if user.picture.blank?
          %td= user.name
          %td.col-md-4.btn-group{"aria-label" => "...", :role => "group"}
            %button.btn.btn-default{:type => "button"}= link_to 'Show', user
            - if user == current_user || current_user.admin
              %button.btn.btn-default{:type => "button"}= link_to 'Edit', edit_user_path(user)
              %button.btn.btn-default{:type => "button"}= link_to 'Destroy', user,                            |
                  method: :delete, data: { confirm: 'Are you sure?' } |
  = will_paginate

app/views/users/new.html.haml
.container
  .row.center-align
    .col.s12.m6.offset-m3.l4.offset-l4
      %h1.orange-text Sign Up
  = render 'form'
  .row
    .col.s12.m6.offset-m3.l4.offset-l4
      Already have an account?
      = link_to "Log in here", login_path, class: 'waves-effect waves-light btn'

app/views/users/show.html.haml
.container
  .row
    #profile-picture.col.s12.m3.l3
      = image_tag(@user.picture, class: 'img-circle img-responsive') if @user.picture?
      = image_tag("#{asset_path('users/image_missing.jpg')}", class: 'img-circle img-responsive') if @user.picture.blank?
    .col.s12.m9.l9
      %p
        = @user.name
      - if logged_in?
        - if @user == current_user || current_user.admin
          %p
            Email:
            = @user.email
          = link_to 'Edit', edit_user_path(@user), class: 'waves-effect waves-light btn'
        - if @user != current_user
          = link_to 'Send message', new_message_path(:user => @user.id), class: 'waves-effect waves-light btn'
      = link_to 'Back', users_path, class: 'waves-effect waves-light btn'