config/routes.rb
Rails.application.routes.draw do

  get 'reset_passwords/new'

  get 'pages/home'
  get 'pages/contact'
  get 'pages/help'

  root to: 'pages#home'

  resources :users do
    member do
      get :activate
    end
  end
  resources :products
  resources :sessions
  resources :reset_passwords, only: [:new, :create, :update, :edit]

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

  get       'signup', to:   'users#new',  as: :signup
  get       'login',  to:   'sessions#new',       as: :login
  post      'login',  to:   'sessions#create'
  delete    'logout', to:   'sessions#destroy',   as: :logout

end

app/controllers/reset_passwords_controller.rb
class ResetPasswordsController < ApplicationController
  skip_before_filter :require_login

  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    @user.deliver_reset_password_instructions! if @user
    flash[:success] = 'Instructions have been sent to your email.'
    redirect_to login_path
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)

    not_authenticated if @user.blank?
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)

    not_authenticated && return if @user.blank?

    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.change_password!(params[:user][:password])
      flash[:success] = 'Password was successfully updated.'
      redirect_to root_path
    else
      render "edit"
    end
  end
end

app/helpers/reset_passwords_helper.rb
module ResetPasswordsHelper
end

app/views/reset_passwords/edit.html.haml
%h1 Choose a new password
= form_for @user, url: reset_password_path(@token), method: :patch do |f|
  = render 'shared/errors', object: @user
  .form-group
    = f.label :password
    = f.password_field :password, class: 'form-control', required: true
  .form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: 'form-control', required: true
  = f.submit 'Set password', class: 'btn btn-primary btn-lg'

app/views/reset_passwords/new.html.haml
%h1 Reset Password
= form_tag reset_passwords_path, method: :post do
  .form-group
    = label_tag :email
    = text_field_tag :email, nil, class: 'form-control', required: true
  = submit_tag "Send reset instructions", class: 'btn btn-primary btn-lg'